version: '3'

services:
    rabbitmq:
      image: rabbitmq:management
      ports:
        - 5672:5672
        - 15672:15672

    emailService:
      image: email-service:latest
      container_name: emailService
      depends_on:
        - rabbitmq
      links:
        - rabbitmq

    javaApp:
        image: todo-list:latest
        container_name: javaApp
        depends_on:
          - rabbitmq
        ports:
          - 9000:9000
        links:
          - rabbitmq